// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/bd_interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/DictAI/Microservices/services/workspace-service/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWorkspacesRepository is a mock of WorkspacesRepository interface.
type MockWorkspacesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspacesRepositoryMockRecorder
}

// MockWorkspacesRepositoryMockRecorder is the mock recorder for MockWorkspacesRepository.
type MockWorkspacesRepositoryMockRecorder struct {
	mock *MockWorkspacesRepository
}

// NewMockWorkspacesRepository creates a new mock instance.
func NewMockWorkspacesRepository(ctrl *gomock.Controller) *MockWorkspacesRepository {
	mock := &MockWorkspacesRepository{ctrl: ctrl}
	mock.recorder = &MockWorkspacesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspacesRepository) EXPECT() *MockWorkspacesRepositoryMockRecorder {
	return m.recorder
}

// CreateWorkspace mocks base method.
func (m *MockWorkspacesRepository) CreateWorkspace(workspace *domain.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspace", workspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkspace indicates an expected call of CreateWorkspace.
func (mr *MockWorkspacesRepositoryMockRecorder) CreateWorkspace(workspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspace", reflect.TypeOf((*MockWorkspacesRepository)(nil).CreateWorkspace), workspace)
}

// FindWorkspace mocks base method.
func (m *MockWorkspacesRepository) FindWorkspace(workspaceID string) (*domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWorkspace", workspaceID)
	ret0, _ := ret[0].(*domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWorkspace indicates an expected call of FindWorkspace.
func (mr *MockWorkspacesRepositoryMockRecorder) FindWorkspace(workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWorkspace", reflect.TypeOf((*MockWorkspacesRepository)(nil).FindWorkspace), workspaceID)
}

// GetByOwnerID mocks base method.
func (m *MockWorkspacesRepository) GetByOwnerID(ownerID string, limit, offset int) ([]*domain.Workspace, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnerID", ownerID, limit, offset)
	ret0, _ := ret[0].([]*domain.Workspace)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOwnerID indicates an expected call of GetByOwnerID.
func (mr *MockWorkspacesRepositoryMockRecorder) GetByOwnerID(ownerID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnerID", reflect.TypeOf((*MockWorkspacesRepository)(nil).GetByOwnerID), ownerID, limit, offset)
}

// UpdateWorkspace mocks base method.
func (m *MockWorkspacesRepository) UpdateWorkspace(workspaceID, name string) (*domain.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspace", workspaceID, name)
	ret0, _ := ret[0].(*domain.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkspace indicates an expected call of UpdateWorkspace.
func (mr *MockWorkspacesRepositoryMockRecorder) UpdateWorkspace(workspaceID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspace", reflect.TypeOf((*MockWorkspacesRepository)(nil).UpdateWorkspace), workspaceID, name)
}

// DeleteWorkspace mocks base method.
func (m *MockWorkspacesRepository) DeleteWorkspace(workspaceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspace", workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkspace indicates an expected call of DeleteWorkspace.
func (mr *MockWorkspacesRepositoryMockRecorder) DeleteWorkspace(workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspace", reflect.TypeOf((*MockWorkspacesRepository)(nil).DeleteWorkspace), workspaceID)
}

// MockParticipantRepository is a mock of ParticipantRepository interface.
type MockParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantRepositoryMockRecorder
}

// MockParticipantRepositoryMockRecorder is the mock recorder for MockParticipantRepository.
type MockParticipantRepositoryMockRecorder struct {
	mock *MockParticipantRepository
}

// NewMockParticipantRepository creates a new mock instance.
func NewMockParticipantRepository(ctrl *gomock.Controller) *MockParticipantRepository {
	mock := &MockParticipantRepository{ctrl: ctrl}
	mock.recorder = &MockParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantRepository) EXPECT() *MockParticipantRepositoryMockRecorder {
	return m.recorder
}

// AddWorkspaceParticipant mocks base method.
func (m *MockParticipantRepository) AddWorkspaceParticipant(participant *domain.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkspaceParticipant", participant)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWorkspaceParticipant indicates an expected call of AddWorkspaceParticipant.
func (mr *MockParticipantRepositoryMockRecorder) AddWorkspaceParticipant(participant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkspaceParticipant", reflect.TypeOf((*MockParticipantRepository)(nil).AddWorkspaceParticipant), participant)
}

// GetWorkspaceParticipants mocks base method.
func (m *MockParticipantRepository) GetWorkspaceParticipants(workspaceID string) ([]*domain.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceParticipants", workspaceID)
	ret0, _ := ret[0].([]*domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceParticipants indicates an expected call of GetWorkspaceParticipants.
func (mr *MockParticipantRepositoryMockRecorder) GetWorkspaceParticipants(workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceParticipants", reflect.TypeOf((*MockParticipantRepository)(nil).GetWorkspaceParticipants), workspaceID)
}

// DeleteParticipant mocks base method.
func (m *MockParticipantRepository) DeleteParticipant(workspaceID, participantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteParticipant", workspaceID, participantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteParticipant indicates an expected call of DeleteParticipant.
func (mr *MockParticipantRepositoryMockRecorder) DeleteParticipant(workspaceID, participantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParticipant", reflect.TypeOf((*MockParticipantRepository)(nil).DeleteParticipant), workspaceID, participantID)
}

// UpdateParticipant mocks base method.
func (m *MockParticipantRepository) UpdateParticipant(workspaceID, participantID, name, email string) (*domain.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipant", workspaceID, participantID, name, email)
	ret0, _ := ret[0].(*domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateParticipant indicates an expected call of UpdateParticipant.
func (mr *MockParticipantRepositoryMockRecorder) UpdateParticipant(workspaceID, participantID, name, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipant", reflect.TypeOf((*MockParticipantRepository)(nil).UpdateParticipant), workspaceID, participantID, name, email)
}
