// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: audio.proto

package audio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioIngestService_GetAudio_FullMethodName = "/audio.AudioIngestService/GetAudio"
)

// AudioIngestServiceClient is the client API for AudioIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioIngestServiceClient interface {
	GetAudio(ctx context.Context, in *GetAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
}

type audioIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioIngestServiceClient(cc grpc.ClientConnInterface) AudioIngestServiceClient {
	return &audioIngestServiceClient{cc}
}

func (c *audioIngestServiceClient) GetAudio(ctx context.Context, in *GetAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioIngestService_ServiceDesc.Streams[0], AudioIngestService_GetAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetAudioRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioIngestService_GetAudioClient = grpc.ServerStreamingClient[AudioChunk]

// AudioIngestServiceServer is the server API for AudioIngestService service.
// All implementations must embed UnimplementedAudioIngestServiceServer
// for forward compatibility.
type AudioIngestServiceServer interface {
	GetAudio(*GetAudioRequest, grpc.ServerStreamingServer[AudioChunk]) error
	mustEmbedUnimplementedAudioIngestServiceServer()
}

// UnimplementedAudioIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioIngestServiceServer struct{}

func (UnimplementedAudioIngestServiceServer) GetAudio(*GetAudioRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method GetAudio not implemented")
}
func (UnimplementedAudioIngestServiceServer) mustEmbedUnimplementedAudioIngestServiceServer() {}
func (UnimplementedAudioIngestServiceServer) testEmbeddedByValue()                            {}

// UnsafeAudioIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioIngestServiceServer will
// result in compilation errors.
type UnsafeAudioIngestServiceServer interface {
	mustEmbedUnimplementedAudioIngestServiceServer()
}

func RegisterAudioIngestServiceServer(s grpc.ServiceRegistrar, srv AudioIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioIngestService_ServiceDesc, srv)
}

func _AudioIngestService_GetAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAudioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioIngestServiceServer).GetAudio(m, &grpc.GenericServerStream[GetAudioRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioIngestService_GetAudioServer = grpc.ServerStreamingServer[AudioChunk]

// AudioIngestService_ServiceDesc is the grpc.ServiceDesc for AudioIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.AudioIngestService",
	HandlerType: (*AudioIngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAudio",
			Handler:       _AudioIngestService_GetAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "audio.proto",
}
