port: 4222

http: 8222

debug: true
trace: true


# потом включим
# tls {
#     cert_file: "/etc/nats/certs/server-cert.pem"
#     key_file: "/etc/nats/certs/server-key.pem"
#     ca_file: "/etc/nats/certs/ca.pem"
# }
